---
# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 4064a18b-1708-467c-8789-46614656e8d1-capi-aws
  namespace: 4064a18b-1708-467c-8789-46614656e8d1
  labels:
    helm.sh/chart: cluster-api-aws-0.5.0
    app.kubernetes.io/name: cluster-api-aws
    app.kubernetes.io/instance: cluster-api-aws
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
